server:
  port: 9002

# jsp setting
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/shop/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true

# mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bunnymarket-db.clihali9mgfh.ap-northeast-2.rds.amazonaws.com:3306/bunny-db
    username: admin
    password: GqyuWLHuGU6gtM4

# mybatis setting
mybatis:
  type-aliases-package: data.*
  mapper-locations:
  - /mapper/**/*.xml