server:
  port: 9002

# jsp setting
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/shop/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true

# mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-bit-final.chytaqpbnviq.us-east-2.rds.amazonaws.com:3306/bit_final
    username: admin
    password: hhg0920*

# mybatis setting
mybatis:
  type-aliases-package: data.*
  mapper-locations:
  - /mapper/**/*.xml